---
title: "TFM tasks"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Master en Bioinformática, Universidad de Murcia
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

# Punto de partida

## Correo botia primera idea

We have a set of samples S with longitudinal omics, and we assume they are free of technical biases.

We want to find a representation of the samples that look for association between specific samples and pathways.

We find a gene clustering (of whatever organization of the genes into groups that is of interest, I don´t care, you tell me), such that for all genes in the gene pool G={g1, g2, .., gn}, we find a clustering C={c1, c2, …, cm} such that all genes in G belong to a c in C, and only one c. Let us suppose that a cluster c in C is of interest to as because it resembles a phenotype (e.g., it is enriched for neurodegeneration related terms) or its expression correlates with case/control status. Based on the genes in c, we find a latent space of samples S. Then we develop a way to find relevant groups of samples within the latent space (e.g., a clustering, an outlier detection algorithm, any other heuristics), such that {sg1, sg2, …, sgk} are sample groups of interest. For all covariates of interest at the clinical data, what we do is to test whether there are significant differences between the covariates of any of the sample groups, in comparison with the rest of samples which do not belong to the group. If we detect such differences, we can say these guys can be identified by the corresponding covariate at the clinical data. If this is it, critical points are

-   How to deal with distances between samples when they are longitudinal

-   How to create the latent space (can be a PCA, but we can use deep learning approaches to find more interesting representations)

-   How to identify the samples, but this is easy.

## Dataset inicial ROS MAP

The Religious Orders Study (ROS) is a longitudinal, epidemiologic clinical-pathological study of memory, motor, and functional problems in older Catholic nuns, priests, and brothers aged 65 years and older from across the United States. Participants without known dementia agree to medical and psychological evaluation each year and brain donation after death. Since 1994, approximately 1,200 older persons have been enrolled and 580 are currently alive. Participants also have yearly blood draws which result in the storage of serum, plasma and cells.

The Memory and Aging Project (MAP) is a longitudinal, epidemiologic clinical-pathologic study of dementia and other chronic diseases of aging. Older persons are recruited from about 40 continuous care retirement communities and senior subsidized housing facilities around the Chicago metropolitan area. Participants without known dementia agree to annual detailed clinical evaluation and donation of brain, spinal cord and muscle after death. MAP began in 1997 and over 1,600 older adults have enrolled. Approximately 1,000 participants are currently alive. Participants also have yearly blood draws which result in the storage of serum, plasma and cells.

-   cogdx = final consensus cognitive diagnosis;

-   age_death = age at death;

-   msex = sex;

-   apoe4 = apoe4 allele count;

-   PMI = post-mortem interval;

-   braaksc = Braak stage;

-   ceradsc = Consortium to Establish a Registry for Alzheimer’s Disease (CERAD) score;

------------------------------------------------------------------------

# TO DO

## Alzheimer

-   [x] clustering con KEGG genes

-   [x] clustering con WGCNA genomewide

    -   [x] Me lo tiene que pasar Alicia

-   [x] Quitar todas las gráficas que sean de batch, RIN, PMI, edad y sexo

    -   [x] Dejar solo las que son braaksc, ceradsc, cogdx, apoe genotype y neuroStatus y study

-   [x] No utilizar test estadísticos porque las dimensiones de los no outliers impide la significancia estadística

-   [ ] Limpiar código

-   [ ] 

------------------------------------------------------------------------

# Correos y reuniones

## **Reunión 2024-01-30**

Empezaremos con datos de Alzheimer

Clasificadores entre casos y controles no porque sea importante el clasificador sino para enfocarnos en los genes

Para determinados grupos de personas, determinar mecanismos concretos en los que para esas personas están enriquecidos

Para un determinado grupo de genes, cuáles son aquellas muestras concretas que están enriquecidas por placas neuríticas en base a esos genes? Encontraríamos un espacio latente de muestras. En base a ese grupo de genes, vamos a representar con UMAP o PCA cuáles son las muestras más extremas, esas son las enriquecidas o empobrecidas en esos genes. No buscamos expresión diferencial. Estamos interesados en detectar muestras, no genes. Buscamos identificar un sujeto que va a sufrir un determinado problema. 

Una estrategia para buscar un espacio latente (buscar estrategia no lineal, PCA o redes neuronales) de modo que maximizamos la oportunidad de encontrar muestras representativas que nos digan algo.

Cogemos los genes, los transformamos y los llevamos a un espacio latente. Cuáles son las muestras más extremas y buscar cuáles de ellas muestran alguna diferencia significativa en alguna covariable de los datos clínicos.

Cómo manejar distancias entre muestras.

Cómo crear el espacio latente.

Cómo identificar las muestras extremas. 

Una vez la pipeline automatizada se puede aplicar a este dataset o a cualquier otro. La idea es crear una herramienta, un paquete de R. 

Para identificar los grupos de genes nos fijamos en términos concretos que sabemos que están presentes en ese dataset. 

Te ayuda a identificar muestras concretas de pacientes concretos para aplicarle un determinado tratamiento.

## **Botia 2024-01-31**

Hola.

Fernando, como primer análisis propongo, en base a las muestras de ROSMAP que puedes encontrar aquí

Por un lado están los datos de expresión, aquí

​rds icon ROSMAP_RINPMIAGESEX_resids.rds

Y por el otro, los metadatos aquí.

​rds icon ROSMAP_RINPMIAGESEX_covs.rds

utilizar un clustering WGCNA genomewide que te va a parar Alicia también pues ya lo tenemos hecho. ¿O se te ocurre otro conjunto de genesets mejor Alicia?

Con ese clustering, lo que tienes es el C={c1, c2, …, cm} de abajo.

Así, un ci de C, con 1 \<= i \<= n, está formado por un número de genes concreto.

Ahora, entonces para cada ci en C, hacemos: paso 1. Nos quedamos solo con la expresión de los genes de ci. Hacemos un PCA de las muestras en base a los genes de ci. Seleccionamos aquellas muestras del PCA tales que el valor del PC1 para la muestra está fuera de 2 veces la desviación típica de los valores de PC1. Es decir, si d es la desviación típica de los valores de PC1, entonces una muestra se selecciona si su PC1 para esa muestra es \> que 2\*d o menor que -2 \* d.

Además, si d2 es la desviación típica de los valores de PC2, entonces una muestra se selecciona si su PC2 para esa muestra es \> que 2\*d2 o menor que -2 \* d2.

Una vez hecho esto, tendremos así tres grupos de muestras, que pueden solaparse. Unas muestras se habrán seleccionado solo por PC1 (lo llamamos mPC1, otras solo por PC2, mPC2, y otras por ambos, mPC12. El resto de muestras que no están en ninguno de esos tres los llamamos M’, siendo M el conjunto total de muestras.

Ahora, lo que tenemos que comprobar es si alguno de los tres grupos de muestras está enriquecido por algún fenotipo interesante, al compararlo con el resto de muestras del PCA dentro de los límites de 2d y 2d2. Es decir, el resto de muestras que no se han seleccionado en NINGUNO de los tres grupos.

¿Cómo hacemos eso?

Nos vamos al fichero de metadatos y buscamos covariables de interés.

Por ejemplo. Supongamos que las muestras que son extremas según PC1 queremos saber si los donantes son más viejos de lo normal. Nos quedamos con la covariable de la edad para todas las muestras.

Seleccionamos en m las muestras extremas según PC1. En m’ las muestras no extremas.

¿Cuál es el fold de la mediana de edad en m con respecto a la mediana de edad en m’?

¿Cuál es el p-valor de un Wilcoxon singned rank sum test? Si es significativo, tenemos una señal.

Y esto lo hacemos para mPC1, mPC2 y mPC3 y toda las covariables que tengamos.

Si la covariable no es numérica, sino que es categórica binaria (e.g., sexo) podemos hacer un Chi cuadrado comparando cómo se distribuye el sexo en el conjunto mPC correspondiente y en M’ y preguntar por el p-valor del test correspondiente.

¿OK?

Por supuesto, si hay alguna duda montamos un zoom rápido.

Ponedme en copia de los emails, porfa.

Salu2

## **Alicia 2024-01-31**

Hola,

Antes de nada, para que no haya dudas, recordar que estos datos ya están corregidos por variables técnicas (efecto batch, RIN, PMI...). Además, también están corregidos por edad y por sexo. Por lo tanto, no deberíamos detectar outliers por ninguna de estas variables (RIN, PMI, sexo o edad). En su lugar, tenemos que fijarnos en el resto de covariables de los donantes, siendo estas braaksc, ceradsc, cogdx e incluso apoe genotype. Todas estas covariables están incluidas en el fichero de metadatos. La columna neuroStatus nos indica si los donantes se clasificaron como controles (0) o como casos de AD (1). Cualquier duda sobre los datos me dices.

Para empezar el análisis, propongo usar un geneset relacionado con el Alzheimer lo más genérico posible para luego ir afinando cada vez más. En este caso, he buscado el termino "Alzheimer disease" en la base de datos KEGG y he extraído la lista de genes asociados con dicho término. Te adjunto el fichero con la lista de genes y copio también el código de R de cómo he obtenido los genes:

library(limma)\
library(AnnotationDbi)\
library(org.Hs.eg.db)\
tab \<- getGeneKEGGLinks(species="hsa")\
tab\$Symbol \<- mapIds(org.Hs.eg.db, tab\$GeneID,\
                       column="SYMBOL", keytype="ENTREZID")\
\
paths \<- getKEGGPathwayNames(species="hsa")\
paths[paths\$PathwayID=="hsa05010", ]\
genes \<- tab\$Symbol[tab\$PathwayID=="hsa05010"]\
write.table(genes, "C:/Users/alici/Downloads/KEGG_hsa05010_genes.txt", quote=FALSE, row.names = F)

Tendrías que coger la matriz de expresión de ROSMAP, quedarte solo con los genes de este geneset que te he pasado y con eso hacer un PCA. Luego, tendrías que extraer las coordenadas del PCA para saber dónde cae cada individuo (eso te lo devuelve la función) y ya determinar qué individuos son outliers y cuáles no con lo que te ha dicho Juan. Empezaría con este geneset a ver qué encontramos. Y luego ya podemos movernos a genesets de términos más concretos o genesets de WGCNA. 

Cualquier cosa nos dices.

## Alicia 

Hola,

ya he podido acceder al html, está muy bien. Te recomiendo que incluyas un table of contents flotante o tabsheets para que sea más fácil ir de una sección a otra del report, ya que cada vez se hará más largo. Al final del report también estaría bien tener la tabla de covariables de los individuos seleccionados como outliers para buscar una posible explicación de porqué son outliers.

Ahora que ya tenemos un punto de partida, el siguiente paso sería probar otros métodos de reducción de la dimensionalidad. Dado que PCA es un método lineal, ahora tocaría probar un método no lineal como UMAP o tSNE. Además, también me gustaría que probáramos otros genesets de AD, esta vez más específicos. Para ello, te propongo usar los genes asociados con AD/demencia detectados con GWAS. En esta review puedes encontrar una tabla suplementaria con estos genes:

[https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(23)00076-2/fulltext](https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(23)00076-2/fulltext "https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(23)00076-2/fulltext")

Cualquier duda nos dices.

Saludos,

Alicia.

## **Alicia 2024-03-19**

Hola!

te paso algunos comentarios del análisis, de momento bastante generales.

\- Lo primero de todo, los datos estaban ya corregidos por batch, RIN, PMI, edad y sexo. Por lo tanto, todos los plots que muestren la distribución de estas covariables se pueden omitir. De esta forma, será más fácil centrarnos en las covariables que realmente nos interesan, siendo estas: braaksc, ceradsc, cogdx, apoe genotype y neuroStatus (study tampoco la descartaría, los outliers pueden venir del mismo estudio). 

\- El tema de si escalar o no los datos en el PCA, es preferible escalar los datos siempre. Los datos que estás usando no están escalados, lo he comprobado.

\- He visto que aplicas tests estadísticos para ver diferencias entre los no outliers y los outliers. No es correcto aplicar tests estadísticos aquí ya que tenemos muy pocos outliers y no tenemos suficiente poder estadístico como para encontrar alguna diferencia. También que los outliers pueden ser outliers por motivos diferentes cada uno, no tiene porqué haber un patrón. De momento, nos limitaremos a los plots y las tablas de covariables para caracterizar mejor a los outliers. Para ello, tenemos los PCA coloreados por covariable y veo que también has incluido barplots. Para que estos últimos sean más informativos, igual quitaría los no outliers de estos plots, ya que están muy representados, dejaría solo los tres tipos de outliers (PC1, PC2 y both) y usaría un geom_bar(stat="identity", position=position_dodge())

\- Por último, en este markdown hace falta un apartado donde se comparen las tres aproximaciones. Para ello, me gustaría ver en un mismo panel de figuras, el PCA, el UMAP y el tSNE obtenidos a partir del mismo conjunto de genes de AD, para ver si hay alguna técnica que separe mejor los individuos que otra. También me gustaría ver el overlap de outliers entre las tres aproximaciones si es posible. Luego, si probamos otros conjuntos de genes de AD como el de GWAS, me gustaría ver la comparativa entre aproximaciones y entre conjuntos de AD. 

Cuando tengas esto, podemos quedar para discutir cosas más concretas de los resultados, gracias!

Saludos,

Alicia.
