---
title: "TFM Alzheimer"
output: html_notebook
---

```{r}
setwd("/Users/fernandolucasruiz/Library/CloudStorage/OneDrive-UNIVERSIDADDEMURCIA/Documentos/Fernando/Master Bioinformatica/TFM")
```

```{r, message=FALSE}
library(tidyverse)

library(limma)
library(AnnotationDbi)
library(org.Hs.eg.db)

library(VennDiagram)
library(grid)

library(ggplot2)
```


```{r}
# covariables
ROSMAP_RINPMIAGESEX_covs <- readRDS("~/Library/CloudStorage/OneDrive-UNIVERSIDADDEMURCIA/Documentos/Fernando/Master Bioinformatica/TFM/datos/ROSMAP_RINPMIAGESEX_covs.rds")
covs <- ROSMAP_RINPMIAGESEX_covs

#datos corregidos 
ROSMAP_RINPMIAGESEX_resids <- readRDS("~/Library/CloudStorage/OneDrive-UNIVERSIDADDEMURCIA/Documentos/Fernando/Master Bioinformatica/TFM/datos/ROSMAP_RINPMIAGESEX_resids.rds")
mat_exp <- ROSMAP_RINPMIAGESEX_resids
```

```{r}
# geneset de Alzheimer extraidos de KEGG

# library(limma)
# library(AnnotationDbi)
# library(org.Hs.eg.db)

tab <- getGeneKEGGLinks(species="hsa")
tab$Symbol <- mapIds(org.Hs.eg.db, tab$GeneID,
                       column="SYMBOL", keytype="ENTREZID")

paths <- getKEGGPathwayNames(species="hsa")
paths[paths$PathwayID=="hsa05010", ]
geneset_alz <- tab$Symbol[tab$PathwayID=="hsa05010"]

```

Vamos a seleccionar solamente los genes de Alzheimer de KEGG en nuestro dataset

```{r}
mat_exp_alz_genes <- mat_exp[, colnames(mat_exp) %in% geneset_alz]
```


Visualizamos si se han seleccionado todos los genes y cuantos del geneset de KEGG

```{r}
#library(VennDiagram)
#library(grid)

venn.plot <- venn.diagram(
  x = list(GenesMatriz = colnames(mat_exp), GenesetAlzheimer = geneset_alz),
  category.names = c("Matrix Genes", "Geneset Alzheimer"),
  filename = NULL,
  output = FALSE,  # Asegura que no se exporte a un archivo
  fill = c("#00CED1", "#E9967A"),
  cex = 1,  # Aumenta el tamaño del texto
  fontface = "bold",
  cat.cex = 1,  # Aumenta el tamaño del texto de las categorías
  cat.fontface = "bold",
  cat.default.pos = "text",
  cat.pos = 25, #posicion de las categoricas
  cat.dist = 0.1, #distancia de las categoricas
  rotation.degree = 0, 
  margin = 0.1, # hacerla más pequeña
  lwd=0, #sin borde
  main = "Alzheimer genes in ROSMAP",
  main.fontface= "bold", 
  main.cex = 2,
  main.pos = c(0.5, 1)
)

# Dibuja el diagrama de Venn generado
grid.newpage()  # Asegura que el lienzo esté limpio
grid.draw(venn.plot)

```



Hacemos PCA de nuestra nueva matriz con los genes seleccionados de Alzheimer

```{r}
pca_alz_genes <- prcomp(mat_exp_alz_genes, scale. = T)
```

```{r}
pca <-  as.data.frame(pca_alz_genes$x)
pca <- cbind(covs, pca)
# Gráfico de componentes principales para cada estado
ggplot(pca, aes(PC1, PC2, color = as.factor(neuroStatus))) +
  modelr::geom_ref_line(h = 0) +
  modelr::geom_ref_line(v = 0) +
  geom_point() +
  #geom_text(aes(label = mrna_id), size = 3) +
  xlab("First Principal Component") +
  ylab("Second Principal Component") +
  ggtitle("First Two Principal Components of Alzheimer ")
```

Seleccionamos muestras que esten 2 veces la desviacion tipica para la PC1

```{r}
outlierspc1 <- as.data.frame(pca_alz_genes$x[abs(pca_alz_genes$x[,1]) > 2*(pca_alz_genes$sdev[1]),1])

outlierspc2 <- as.data.frame(pca_alz_genes$x[abs(pca_alz_genes$x[,2]) > 2*(pca_alz_genes$sdev[2]),2])
```

Las ploteamos 

```{r}
plot1 <- ggplot(df, aes(x = PC1)) +
  geom_density(fill = "#00CED1", alpha = 0.5) +
  geom_vline(xintercept = mean(df$PC1) + 2*pca_alz_genes$sdev[1], linetype = "dashed", color = "blue") +
  geom_vline(xintercept = mean(df$PC1) - 2*pca_alz_genes$sdev[1], linetype = "dashed", color = "blue") +
  labs(title = "PC1 density with 2*SD") +
  geom_text(data = outlierspc1, 
            aes(x = outlierspc1[,1], y= 0, label = rownames(outlierspc1)), 
            vjust = 1.5, hjust = 0, size = 3, color = "#E9965A", angle = 90, fontface= "bold") +
  geom_rug(data = as.data.frame(pca_alz_genes$x), aes(x= PC1, y = 0), color= ifelse(abs(pca_alz_genes$x[,1]) > 2*(pca_alz_genes$sdev[1]), "black", "grey")) +
  theme_minimal()

plot2 <- ggplot(df, aes(x = PC2)) +
  geom_density(fill = "#00CED1", alpha = 0.5) +
  geom_vline(xintercept = mean(df$PC2) + 2*pca_alz_genes$sdev[2], linetype = "dashed", color = "blue") +
  geom_vline(xintercept = mean(df$PC2) - 2*pca_alz_genes$sdev[2], linetype = "dashed", color = "blue") +
  labs(title = "PC2 density with 2*SD") +
  geom_text(data = outlierspc2, 
            aes(x = outlierspc2[,1], y= 0, label = rownames(outlierspc2)), 
            vjust = 1.5, hjust = 0, size = 3, color = "#E9965A", angle = 90, fontface= "bold") +
  geom_rug(data = as.data.frame(pca_alz_genes$x), aes(x= PC2, y = 0), color= ifelse(abs(pca_alz_genes$x[,2]) > 2*(pca_alz_genes$sdev[2]), "black", "grey")) +
  theme_minimal()

grid.arrange(plot1, plot2, ncol = 1)
```






